metricbeat.modules:
- module: postgresql
  enabled: true
  metricsets: [ database, bgwriter, activity ]
  period: 10s
  hosts: ["postgres://postgres:5432?sslmode=disable"]
  username: postgres
  password: xpressolab

output.elasticsearch:
  hosts: [ "elasticsearch:9200" ]
  template.name: "metricbeat"
  template.path: "metricbeat.template.json"
  template.overwrite: false

