packetbeat.interfaces.device: any

packetbeat.interfaces.buffer_size_mb: 30

packetbeat.protocols.dns:
  ports: [53]
  include_authorities: true
  include_additionals: true

packetbeat.protocols.http:
  enabled: false
  ports: [80, 5601, 9200, 8080, 8081, 5000, 8002]

packetbeat.protocols.memcache:
  ports: [11211]

packetbeat.protocols.mysql:
  enabled: false
  ports: [3306]

packetbeat.protocols.pgsql:
  enabled: false
  ports: [5432]
  send_request: true
  send_response: true

packetbeat.protocols.redis:
  enabled: false
  ports: [6379]

packetbeat.protocols.thrift:
  enabled: false
  ports: [9090]

packetbeat.protocols.mongodb:
  enabled: true
  ports: [27017]
  send_request: true
  send_response: true

packetbeat.protocols.cassandra:
  enabled: false
  ports: [9042]

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['172.0.2.1:9200']
  index: packetbeat-%{+YYYY.MM.dd}
  # username: elastic
  # password: changeme
