version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    container_name: elasticsearch
    mem_limit: 1g
    environment:
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.0
    container_name: logstash
    mem_limit: 1g
    ports: [ "5000:5000", "9600:9600", "8000:8000" ]
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    volumes: [ "./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf", "./logs:/tmp/logs" ]
    depends_on: [ elasticsearch ]

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.0
    container_name: kibana
    mem_limit: 1g
    environment:
      - "xpack.security.enabled=false"
    volumes:
      - "./config/kibana.yml:/usr/share/kibana/config/kibana.yml"
    ports:
      - 5601:5601
    depends_on: [elasticsearch]
